/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-tertiary-container": "#838484",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-fixed": "#1b1b1b",
        "tertiary-container": "#1a1c1c",
        "secondary": "#5f5e5e",
        "on-secondary-fixed-variant": "#474646",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f4",
        "surface-bright": "#f9f9f9",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f1f1",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-container": "#656464",
        "surface-variant": "#e2e2e2",
        "surface": "#f9f9f9",
        "primary-container": "#1b1b1b",
        "tertiary": "#000000",
        "outline-variant": "#cfc4c5",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-surface": "#2f3131",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e3e2e2",
        "surface-dim": "#dadada",
        "on-primary-container": "#848484",
        "on-error": "#ffffff",
        "background": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "inverse-primary": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e5e2e1",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-surface-variant": "#4c4546",
        "outline": "#7e7576",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c1c",
        "secondary-fixed-dim": "#c8c6c5"
      },
      fontFamily: {
        "headline": ["var(--font-newsreader)", "serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"],
        "raleway": ["var(--font-raleway)", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
