/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#5d5f5f",
        "secondary-fixed": "#c8c6c6",
        "tertiary-fixed": "#5d5f5f",
        "on-primary-fixed": "#ffffff",
        "on-secondary-fixed": "#1c1b1c",
        "on-tertiary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-secondary-fixed-variant": "#3c3b3b",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "primary-container": "#d4d4d4",
        "secondary-container": "#474647",
        "tertiary-container": "#909191",
        "on-primary-container": "#000000",
        "on-secondary-container": "#e5e2e1",
        "on-tertiary-container": "#000000",
        "surface-container": "#201f1f",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "on-surface-variant": "#c6c6c6",
        "outline": "#919191",
        "outline-variant": "#474747",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#5d5f5f",
        "surface-tint": "#c6c6c7",
        "secondary-fixed-dim": "#adabaa",
        "tertiary-fixed-dim": "#454747",
        "primary-fixed-dim": "#454747",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-background": "#e5e2e1",
        "background": "#131313",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "on-primary": "#1a1c1c",
        "on-secondary": "#1c1b1c",
        "on-tertiary": "#1a1c1c",
        "primary": "#ffffff",
        "secondary": "#c8c6c6",
        "tertiary": "#e2e2e2"
      },
      fontFamily: {
        "headline": ["var(--font-newsreader)", "serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"],
        "raleway": ["var(--font-raleway)", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
